# Generated by Django 5.2.7 on 2026-01-28 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp'])])),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF Document')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_by', models.CharField(default='Anonymous', max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['file_type', '-upload_date'], name='filemanager_file_ty_c2c492_idx'), models.Index(fields=['uploaded_by'], name='filemanager_uploade_72bf0f_idx')],
            },
        ),
    ]
